cohstats/coh3-stats

components/Icons/Donate.tsx

- Wrap Donate btn's image in donate url's link, open in new tab

Add link to the donate button

---

components/Icons/Discord.tsx
components/Icons/Donate.tsx

- Wrap Discord btn in anchor instead of Fragment
- Move Donate btn's anchor wrapping above IconButton and replace Fragment

8 add link to the discord button

---

package.json
pages/leaderboards.tsx
yarn.lock

Implemented as much of the table as possible using currently available data and components. Does not include the `change` column since I couldn't find firestore in the current version. Does not include the `country flag component` since that component is not implemented yet. I was getting a CORS error using fetch so I tested with hardcoded data retrieved from postman, so the fetch response might need to be adjusted.

resolves #16. Added table for currently available data and components.

---

components/Header/Header.tsx
components/icon/steam.tsx
pages/_app.tsx
pages/leaderboards.tsx
pages/players/[playerID].tsx
util/factions.ts

Advanced leaderboard navigation

---

pages/_app.tsx

add reset debouncedQuery when to close spotlight

---

components/customSpotlightProvider.tsx
pages/_app.tsx

create CustomSpotlightProvider.tsx for performance
change onChange -> onQueryChange because only spotlight text need

Fix Spotlight loading indicator state

---

pages/_app.tsx

https://github.com/cohstats/coh3-stats/issues/60

Add system colorscheme preference detection

---

components/player-card/player-recent-matches.tsx

issue #71
Just change effect to memo.

Fix PlayerRecentMatches showing No Records for a moment

---

components/player-card/player-standings-table.tsx
pages/leaderboards.tsx

Fix Leaderboards Datatable unique key

---

components/customSpotlightProvider.tsx

We are getting a lot of requests for the search function

Increase search debounce

---

components/internal-timeago.tsx

https://github.com/cohstats/coh3-stats/issues/87

feat: add match timeago tooltip

---

components/player-card/filterable-header.tsx

Fix Filter on the table is not visible when there are no data

---

pages/explorer/races/[raceId].tsx
src/unitStats/faction.ts
src/unitStats/mappingEbps.ts
src/unitStats/mappingSbps.ts
src/unitStats/unitStatsLib.ts

- Turn off the console logs I put for debugging within the faction page.
- Remove obsolete comments and cases within the mappings.
- Add `british_africa` so the faction page works again.
Ready to merge.

Small cleanup mappings

---

components/internal-timeago.tsx
components/other/beta-version.tsx
components/player-card/player-standings.tsx
components/player-card/player-summary.tsx
components/player-card/standings/faction-summary.tsx
components/player-card/standings/player-standings-faction.tsx
components/player-card/standings/player-standings-table.tsx
pages/players/[playerID].tsx
src/coh3/coh3-types.ts
src/players/utils.ts

Fixes also https://github.com/cohstats/coh3-stats/issues/111

Improved player card

---

pages/explorer/dps.tsx
pages/explorer/races/[raceId].tsx
pages/explorer/races/[raceId]/units/[unitId].tsx
routes.ts
src/utils.ts

Improve the unit pages

---

components/twitch-panel/twitch-panel.tsx
pages/index.tsx

fix: Twitch Stream freezes when back to home

---

components/unitStats/dpsChart.tsx
src/unitStats/mappingWeapon.ts

- Small Mapping Fix regarding long range cooldown multiplier
- Disclaimer added

Dps tool - Bug Fix

---

components/Header/components/ExplorerMenu.tsx
src/routes.ts

Allows navigation to units page.

Restructure explorer header links

---

components/twitch-panel/twitch-panel.tsx
src/utils.ts

want to test on the dev edgio deployment. The idea to check this way is from https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent `Use [Navigator.maxTouchPoints](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints) to detect if the user's device has a touchscreen.`
https://github.com/cohstats/coh3-stats/issues/149

only autoplay twitch player if not on touchscreen

---

components/unitStats/dpsChart.tsx

@chris-nos  you are right, it's super stupid. I am baffled that you can't set it up simply.
But I found this code which is little bit cleaner, in the end it probably doesn't matter much but I think we could use it like this.

Width fix on selector

---

components/dev-site-notification.tsx
pages/_app.tsx

https://github.com/cohstats/coh3-stats/issues/173
not sure if it's in the best spot, let me know. It's in `_app.tsx`

add a dialog if not on coh3stats.com (such as dev site) https://github.com/cohstats/coh3-stats/issues/173

---

components/unit-cards/battlegroup-card.tsx
components/unit-cards/building-description-card.tsx
components/unitStats/unitTable.tsx
pages/explorer/index.tsx
pages/explorer/races/[raceId]/units/index.tsx
src/routes.ts
src/unitStats/dpsCommon.ts

- Upkeep column
- Allow redirect on row click
- Minor styling changes.

Unit Browser Table Improvements

---

pages/index.tsx

Add DPS and Unit browser cards at home

---

config.ts
src/unitStats/mappingEbps.ts
src/unitStats/workarounds.ts

Now using the mod, towed guns get the correct weapon and so does the weasel.

Workaround config update

---

components/Header/Header.tsx
components/Header/components/ExplorerMenu.tsx
components/Header/components/StatisticsMenu.tsx
src/coh3/coh3-data.ts

Fixes https://github.com/cohstats/coh3-stats/issues/202
Fixes https://github.com/cohstats/coh3-stats/issues/200
Fixes https://github.com/cohstats/coh3-stats/issues/199

Little UI fixes and tweaks

---

components/unit-cards/unit-squad-card.tsx
components/unitStats/dpsUnitCustomizing.tsx
pages/explorer/races/[raceId]/units/[unitId].tsx
src/unitStats/faction.ts
src/unitStats/mappingEbps.ts

- Added acceleration and deceleration values.
- Fixed the missing "flak_gun" type within the ebps.

Minor fixes 120

---

src/coh3/coh3-data.ts

Fix the benghazi url

---

components/unitStats/dpsChart.tsx
components/unitStats/dpsUnitCustomizing.tsx
src/unitStats/mappingEbps.ts
src/unitStats/mappingSbps.ts
src/unitStats/mappingWeapon.ts

Somehow the weapon (and probably other stats) weren't updating when user picked a different patch version at the DPS Tool.

Fix DPS tool weapon loading

---

config.ts

Waiting for the data to be live at coh3-data :)

Set latest patch as 1.2.2

---

src/unitStats/locstring.ts

I think it's OK to pull this from the tags and not from master right?

Pull data from versioned locstring

---

.gitignore
README.md
components/Footer/Footer.tsx
components/Header/components/OtherMenu.tsx
components/leaderboards/leaderboard-stats.tsx
components/online-players.tsx
components/screens/about/AboutUs.tsx
components/screens/home/info-cards.tsx
components/unitStats/dpsChart.tsx
pages/desktop-app.tsx
pages/explorer/races/[raceId].tsx
pages/other/open-data.tsx
pages/other/player-export.tsx
pages/other/ranking-tiers.tsx
pages/stats/leaderboards.tsx
pages/stats/players.tsx

[FIXED] grammatical errors in the UI

---

components/Header/components/StatisticsMenu.tsx
screens/stats/achievements/achievement.tsx
screens/stats/achievements/index.tsx
src/routes.ts

Closes https://github.com/cohstats/coh3-stats/issues/272

Create achievement page

---

components/unit-cards/unit-cost-card.tsx
components/unit-cards/weapon-loadout-card.tsx
pages/explorer/races/[raceId]/units/[unitId].tsx
src/unitStats/mappings.ts

- Add reinforce cost card at the unit details.
- Add some multipliers to the weapon card.

Reinforce cost stats

---

components/unit-cards/battlegroup-card.tsx
components/unit-cards/unit-upgrade-card.tsx
pages/explorer/races/[raceId].tsx
src/unitStats/locstring.ts
src/unitStats/mappingEbps.ts
src/unitStats/mappingSbps.ts
src/unitStats/mappingUpgrades.ts
src/unitStats/workarounds.ts

- Brief text formatter improvements for upgrades and squads.
- Add workarounds for the new battlegroups so we can redirect on click to unit stats page.
- Add a new selector for those battlegroup call-ins that consist of more than 2 squads.

Overall BG Improvements

---

config.ts

- Data tag added for 1.4.2
- Added tag for the 1.3.x range.

Update with data from 1.4.2

---

components/unit-cards/unit-squad-card.tsx
components/unitStats/dpsUnitCustomizing.tsx
pages/explorer/races/[raceId]/units/[unitId].tsx
src/unitStats/workarounds.ts

- Add cap and decap multipliers to unit card.
- Add unit options for the two new battlegroups.

Minor improvements to unit stats

---

package.json
yarn.lock

Reverts cohstats/coh3-stats#413

Revert "Update dependency eslint to v9"

---

components/Header/Header.tsx
components/unit-cards/unit-upgrade-card.tsx
pages/explorer/races/[raceId].tsx
screens/news/index.tsx
src/unitStats/dpsCommon.ts
src/unitStats/locstring.ts
src/unitStats/workarounds.ts

- Fixed upgrade cost of Australian Infantry to 280 via workaround.
- Fixed the formatter to take into account locstring values.
- Used floating tooltips for long brief / extra texts.
- Fix weapon list filter of those weapons dealing zero damage (excluding artillery ones).

Cleanup Unit Stats Section

---

components/unit-cards/battlegroup-card.tsx
components/unit-cards/building-description-card.tsx
components/unit-cards/requirement-card.tsx
components/unit-cards/unit-description-card.tsx

- Added brief text to BG card.
- Added brief text formatting for Requirements and Building Cards.

Minor Improvements to Cards - Brief Texts

---

src/unitStats/mappingAbilities.ts

Rhe abilities now take into account the child requirements introduced at 1.7.0

Fix: Abilities Requirements Mapping

---

src/unitStats/mappingSbps.ts

Fix mapping

---

components/unit-cards/battlegroup-card.tsx
config.ts
src/unitStats/workarounds.ts

Patch Update 2.0.1

---

pages/players/[...playerID].tsx
screens/players/tabs/standings-tab/player-standings-tab.tsx
screens/players/tabs/standings-tab/player-standings-table.tsx
screens/players/tabs/standings-tab/widgets/alias-history-widget.tsx
src/coh3/coh3-types.ts

Add alias history to the player cards
